import type { Metadata } from 'next'
import { notFound } from 'next/navigation'
import { getQuestionnaireByToken, getLatestAnswerForQuestionnaire } from '@/lib/db/questionnaires'
import { getJdTitleById } from '@/lib/db/jd-history'
import type { Question } from '@/lib/db/types'
import PrintTrigger from './PrintTrigger'
import PrintButton from './PrintButton'

export async function generateMetadata({
  params,
}: {
  params: Promise<{ token: string }>
}): Promise<Metadata> {
  const { token } = await params
  const q = await getQuestionnaireByToken(token)
  const jobTitle = q?.jd_history_id ? await getJdTitleById(q.jd_history_id) : null
  return { title: `Jane AI - ${jobTitle ?? 'Hiring Brief'}` }
}

function formatSubmittedAt(iso: string): string {
  const d = new Date(iso)
  if (isNaN(d.getTime())) return iso
  return d.toLocaleString('vi-VN', {
    hour: '2-digit',
    minute: '2-digit',
    day: '2-digit',
    month: '2-digit',
    year: 'numeric',
    weekday: 'long',
    timeZone: 'Asia/Ho_Chi_Minh',
  })
}

function renderAnswer(question: Question, answers: Record<string, unknown>): string {
  const value = answers[question.id]
  if (value == null) return '(chưa trả lời)'

  if (question.type === 'skill_matrix' && Array.isArray(value)) {
    return value
      .map((v) => {
        if (typeof v === 'object' && v !== null && 'skill' in v) {
          const s = v as { skill?: string; level?: string }
          if (typeof s.skill !== 'string') return String(v)
          return s.level ? `${s.skill} [${s.level}]` : s.skill
        }
        return String(v)
      })
      .join(' · ')
  }

  if (Array.isArray(value)) return value.map(String).join(', ')
  return String(value)
}

export default async function SummaryPrintPage({
  params,
}: {
  params: Promise<{ token: string }>
}) {
  const { token } = await params

  const q = await getQuestionnaireByToken(token)
  if (!q) notFound()

  const jobTitle = q.jd_history_id ? await getJdTitleById(q.jd_history_id) : null
  const ans = await getLatestAnswerForQuestionnaire(q.id)

  if (!ans) {
    return (
      <div className="min-h-screen flex items-center justify-center text-gray-500 text-sm">
        Sếp chưa điền bảng hỏi này.
      </div>
    )
  }

  const questions = q.questions as Question[]
  const answers = ans.answers as Record<string, unknown>

  const sections = questions.reduce<Record<number, { label: string; questions: Question[] }>>(
    (acc, question) => {
      if (!acc[question.section]) {
        acc[question.section] = { label: question.sectionLabel, questions: [] }
      }
      acc[question.section].questions.push(question)
      return acc
    },
    {}
  )

  return (
    <>
      <PrintTrigger />
      <style>{`
        @media print {
          .no-print { display: none !important; }
          body { font-size: 11pt; }
          .page-break { page-break-before: always; }
        }
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; }
      `}</style>

      <div className="max-w-2xl mx-auto px-8 py-10">
        <div className="no-print flex justify-end mb-6">
          <PrintButton />
        </div>

        <div className="border-b-2 border-gray-800 pb-4 mb-6">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-xs font-bold text-indigo-600 uppercase tracking-widest">Jane AI · Hiring Brief</p>
              <h1 className="text-2xl font-bold text-gray-900 mt-1">{jobTitle ?? 'Không rõ vị trí'}</h1>
            </div>
          </div>
          <p className="text-sm text-gray-500 mt-2">
            Submitted: {formatSubmittedAt((ans.submitted_at ?? new Date()).toISOString())}
          </p>
        </div>

        <div className="space-y-7">
          {Object.entries(sections)
            .sort(([a], [b]) => Number(a) - Number(b))
            .map(([sectionNum, { label, questions: sqs }]) => (
              <div key={sectionNum}>
                <h2 className="text-xs font-bold text-gray-400 uppercase tracking-widest border-b border-gray-200 pb-1 mb-3">
                  {label}
                </h2>
                <div className="space-y-4">
                  {sqs.map((question) => (
                    <div key={question.id}>
                      <p className="text-xs font-semibold text-gray-500 mb-1">{question.text}</p>
                      <p className="text-sm text-gray-800 leading-relaxed">
                        {renderAnswer(question, answers)}
                      </p>
                    </div>
                  ))}
                </div>
              </div>
            ))}
        </div>

        <div className="mt-10 pt-4 border-t border-gray-200 text-center">
          <p className="text-xs text-gray-400">Generated by Jane AI · jane-ai.app</p>
        </div>
      </div>
    </>
  )
}
