'use client'

import { SignInButton, useClerk } from '@clerk/nextjs'
import { useEffect, useState } from 'react'

function isInAppBrowser() {
  if (typeof window === 'undefined') return false
  const ua = navigator.userAgent
  return /FBAN|FBAV|FB_IAB|Instagram|Line|Twitter|TikTok|Snapchat|LinkedIn|Pinterest|WeChat|MicroMessenger|Zalo/.test(ua)
}

// Google blocks OAuth inside in-app webviews, so the sign-in modal opened from
// the tip popup hides the social buttons + divider, leaving only the email-code
// form. Pass style objects (not class strings): Clerk emits them as CSS-in-JS
// classes that out-specify its own defaults. A Tailwind `hidden` class is never
// generated by v4's JIT, and a plain globals.css rule does not survive the build,
// so both of those approaches leave Google visible.
const emailOnlyAppearance = {
  elements: {
    socialButtonsRoot: { display: 'none' },
    socialButtons: { display: 'none' },
    dividerRow: { display: 'none' },
  },
}

interface Props {
  children: React.ReactNode
  className?: string
}

export default function InAppBrowserSignIn({ children, className }: Props) {
  const [inApp, setInApp] = useState(false)
  const [showTip, setShowTip] = useState(false)
  const clerk = useClerk()

  useEffect(() => {
    const timer = setTimeout(() => {
      setInApp(isInAppBrowser())
    }, 0)
    return () => clearTimeout(timer)
  }, [])

  if (!inApp) {
    return (
      <SignInButton mode="modal">
        <button className={className}>{children}</button>
      </SignInButton>
    )
  }

  return (
    <div className="relative">
      <button
        className={className}
        onClick={() => setShowTip(true)}
      >
        {children}
      </button>
      {showTip && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-6 bg-black/50" onClick={() => setShowTip(false)}>
          <div className="bg-white rounded-2xl p-6 max-w-sm w-full shadow-xl" onClick={e => e.stopPropagation()}>
            <div className="w-12 h-12 bg-orange-100 rounded-full flex items-center justify-center mx-auto mb-4">
              <svg className="w-6 h-6 text-orange-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01M10.29 3.86L1.82 18a2 2 0 001.71 3h16.94a2 2 0 001.71-3L13.71 3.86a2 2 0 00-3.42 0z" />
              </svg>
            </div>
            <h3 className="text-center font-semibold text-gray-900 text-lg mb-2">
              Đăng nhập trong app
            </h3>
            <p className="text-center text-gray-500 text-sm leading-relaxed mb-5">
              Google không cho phép đăng nhập trong trình duyệt của app. Bạn có thể đăng nhập bằng <strong>email</strong> ngay tại đây, hoặc mở bằng <strong>Safari</strong>/<strong>Chrome</strong> để dùng Google.
            </p>
            <div className="space-y-2">
              <button
                className="w-full bg-[#1B2B6E] text-white py-3 rounded-full font-medium text-sm"
                onClick={() => {
                  setShowTip(false)
                  clerk.openSignIn({ appearance: emailOnlyAppearance })
                }}
              >
                Đăng nhập bằng email
              </button>
              <button
                className="w-full text-gray-600 py-2 text-sm underline"
                onClick={() => {
                  // copy current URL to clipboard
                  navigator.clipboard?.writeText(window.location.href).catch(() => {})
                  setShowTip(false)
                  alert('Đã copy link! Mở Safari hoặc Chrome và paste vào thanh địa chỉ nhé.')
                }}
              >
                Mở Safari/Chrome để dùng Google
              </button>
              <button
                className="w-full text-gray-400 py-2 text-sm"
                onClick={() => setShowTip(false)}
              >
                Đóng
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
